version: '3'


services:
    db:
        image: postgres
        environment: 
            - POSTGRES_DB=shop
            - POSTGRES_USER=achi
            - POSTGRES_PASSWORD=ptnshop
    
    web:
        build: .
        command: bash -c 'python3 shop/manage.py migrate && python3 shop/manage.py runserver 0.0.0.0:8000'
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
        depends_on: 
            - db