version: '3'


services:
    db:
        image: postgres
        environment: 
            - POSTGRES_DB=shop
            - POSTGRES_USER=achi
            - POSTGRES_PASSWORD=ptnshop
    
    web:
        build: .
        env_file: 
            - shop/.env
        command: bash -c 'python3 shop/manage.py collectstatic --no-input --clear && python3 shop/manage.py migrate && cd shop && gunicorn --bind 0.0.0.0:8000 shop.wsgi'
        volumes: 
            - .:/code
        expose: 
            - 8000
        depends_on: 
            - db
    
    nginx:
        build: ./nginx
        ports: 
            - 8000:80
        depends_on: 
            - web

