# Generated by Django 3.0.4 on 2020-04-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200406_1415'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productitem',
            managers=[
            ],
        ),
    ]
