# Generated by Django 3.0.4 on 2020-04-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='cart_obj', to='carts.CartItem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='carts.Cart'),
        ),
    ]
