# Generated by Django 3.0.4 on 2020-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200410_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='cart_items', to='carts.CartItem'),
        ),
    ]
