# Generated by Django 3.0.4 on 2020-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200406_1415'),
        ('carts', '0006_remove_cart_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_item',
            field=models.ManyToManyField(related_name='product_in_cart', to='products.ProductItem'),
        ),
    ]
